services:
  - type: web
    name: masjid-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /api/ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      # You can add MONGO_URI and JWT_SECRET here via the Render dashboard later
